### ISSUE TITLE
New issue in updated SPM to display slices in Elvis

### ISSUE THREAD

**Issue by andreashorn** [leaddbs/leaddbs#138]
Old SPM version (e.g. 6906):
V=spm_vol('file.nii');
A=V.private.dat;
A(50,:,:) -> Gives out values.

Newest SPM version (7219):
The same gives this error:

Error using file2mat
Indices must be int32.

Error in file_array/subsref>multifile2mat (line 179)
   val(cc(i)+1:cc(i+1)) = file2mat(obj,int64(1),int64(x(y==i)));

Error in file_array/subsref>subfun (line 99)
   t = multifile2mat(sobj,varargin{:});

Error in file_array/subsref (line 65)
   t = subfun(sobj,args{:});

**Comment by andreashorn** [comment]
GF suggests we should use nifti() instead
https://www.jiscmail.ac.uk/cgi-bin/webadmin?A2=ind1801&L=spm&D=1&O=D&X=20381242B896E5812E&Y=andreas.horn%40charite.de&P=410866

Best

**Comment by ningfei** [comment]
Yes, I checked SPM svn change log, there's some changes regarding file2mat, but this should not break the use of `nii.private.dat`. For this error, it's probably because the mex file on Frederike's machine is not actually updated. That's why I can't reproduce the error here. We could either update the code to use `nifti` or leave it as it is.

**Comment by andreashorn** [comment]
Agreed. In any case there is no rush and we need to fix the .mex file on FI's computer. Still, probably sooner or later switching to nifti for this would be more stable.

**Comment by ningfei** [comment]
Agreed, `private` member of the structure is not supposed to be used the way as we do I guess.
